### ISSUE TITLE
Missing information - Message

### ISSUE THREAD

**Issue by kristo2301** [mjiderhamn/worx-landroid-nodejs#11]
Hello I just try to connect to my Landroid and result of log are missing information - **BOLD below**  i think is more missing in API 

{"versione_fw":2.47,"lingua":0,"ore_funz":[54,54,54,54,54,0,0],"ora_on":[9,9,9,9,9,0,0],"min_on":[0,0,0,0,0,0,0],"allarmi":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"settaggi":[0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"mac":[0,35,167,165,16,64],"time_format":1,"date_format":1,"rit_pioggia":180,"area":0,"enab_bordo":1,"percent_programmatore":0,"indice_area":9,"tempo_frenatura":20,"perc_rallenta_max":70,"canale":0,"num_ricariche_batt":0,"num_aree_lavoro":1,"dist_area":[1,1,1,1],"perc_per_area":[1,1,1,1],"area_in_lavoro":0,"email":"xxxxxxx","perc_batt":"88","ver_proto":1,"state":"idle","workReq":"user req grass cut","**message":"wire missing"**,"batteryChargerState":"idle","distance":0}

**Comment by mjiderhamn** [comment]
Thanks for the report. This is related to #1, so I'll close this issue and continue there.
