### ISSUE TITLE
Battery percentage 0

### ISSUE THREAD

**Issue by rootje** [mjiderhamn/worx-landroid-nodejs#18]
landroid-cloud2domoticz.js shows the following in the output:

Landroid status: {"state":"Mowing","errorMessage":null,"batteryPercentage":null,"totalMowingHours":44

Domotics UI shows 0.00% in the "Worx Landroid Battery" section.

Is this a known issue?

**Comment by mjiderhamn** [comment]
AFAI understand there is no battery percentage in the official app either, and it looked like there was no value for it in the data provided by the server. If introduced into the data stream, it should be easy to add to this library.

**Comment by rootje** [comment]
The app shows a battery indication, where does it get it's information? However there is no percentages, there is a symbol that represents full or half full. It would be great to add it as soon as the data is present!

**Comment by Bouni** [comment]
There is battery data in the data received from MQTT but it is only visualized in the as of Version 1.7.
` bt: { t: 15.4, v: 19.52, p: 82, nr: 3082, c: 0 }` 
These values are all related to the batteries

- t: temperature
- v: voltage
- p: loading level in percent
- nr: number of charging cycles
- c: indicator if its charging at the moment

**Comment by rootje** [comment]
Hello! Thank you for your reply. 
I'm sorry, but I don't quite follow:

> but it is only visualized in the as of Version 1.7

Where is it visualized (in the ??? as of Version 1.7) and what should be version 1.7? This project, a Landroid implementation, ...?? Please help! 

Thanks you!

**Comment by MagnusKlingenberg** [comment]
I have a pull request up for the battery percentage at #21

**Comment by Bouni** [comment]
@rootje 
Sorry for the confusion, @MagnusKlingenberg is right, I was talking about the Android App Version 1.7.
In prior versions of the App the data for the battery was transmitted but not visualized!

**Comment by rootje** [comment]
Thanks guys!

**Comment by MagnusKlingenberg** [comment]
@rootje Now that #21 has been merged. Is the problem still there for you?

**Comment by rootje** [comment]
@MagnusKlingenberg problem is solved! Although #25 did not work for me (as the latest version) #24 did. The battery percentage is now shown! Thank you very much!
