### ISSUE TITLE
Error: certificate has expired

### ISSUE THREAD

**Issue by Bouni** [mjiderhamn/worx-landroid-nodejs#19]
Hi,

has anybody the same problem that node throws an error "Error: certificate has expired"? (Landroid 2017 models)

```
UUID: f7c04c40-a9e1-11e7-be14-2db3fc03e9e7
Downloaded guest token
API token set to <redacted>
Logged in as <redacted> - user token retrieved from API
API token set to <redacted>
Certificate retrieved
Fetching root CA
Connecting to MQTT broker
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1108:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:638:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:468:38)
```
Any ideas?

Maybe it has something to do with reported [cloud connection issues ](https://trello.com/c/t5US9QbP/92-want-to-contribute-read-here#comment-59cbe36ebc53d5a116953244)

**Comment by iMartien** [comment]
Yep, having the same issue..

**Comment by Bouni** [comment]
I simply don't understand which certificate is out of date!?

My user cert which I get from the API is OK:
```
Common Name: AWS IoT Certificate
Valid From: May 8, 2017
Valid To: December 31, 2049
Serial Number: 6a761b5ba56b4608fad03895b3e73f419592e8cc
```
as well as the CA cert from Symantec:
```
Common Name: VeriSign Class 3 Public Primary Certification Authority - G5
Organization: VeriSign, Inc.
Organization Unit: VeriSign Trust Network
Country: US
Valid From: November 7, 2006
Valid To: July 16, 2036
Issuer: VeriSign Class 3 Public Primary Certification Authority - G5, VeriSign, Inc.
Serial Number: 18dad19e267de8bb4a2158cdcc6b3b4a
```
Any ideas where to search for the problem?

**Comment by mjiderhamn** [comment]
It could be the TLS certificate used to encrypt the connection (rather than the client certificate used for authentication). The stack trace of the error message supports that theory.

**Comment by JRB202** [comment]
Same cert problem with me :  See below

I have this new error since I upgraded my landroid WR105SI to firmware V2.85.

I have read in a forum that worx has changed their hosting provider in this new firmware ...
It could be related to this issue ...

Connecting to MQTT broker at mqtt://localhost...
Connected to MQTT broker
Connected to Domoticz MQTT, connect to Landroid MQTT
Downloaded guest token
API token set to qiJNxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Logged in as xxxxxxxxxxx@gmail.com - user token retrieved from API
API token set to RTrxTOyaqUxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Certificate retrieved
Fetching root CA
Connecting to Landroid MQTT broker
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:188:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)

**Comment by Bouni** [comment]
Just downloaded an decompiled the latest APK (1.7), it seems they still use Amazon AWS IoT:

```
public class MQTTWrapper {                                                                                                                                                      
    private static final String CUSTOMER_SPECIFIC_ENDPOINT = "a1optpg91s0ydf-2.iot.eu-west-1.amazonaws.com"; 
```

**Comment by Bouni** [comment]
I also found out that the GuestToken seems to be the same for all users, the anonymous downloaded APK has the same GuestToken as the one from PasteBin

**Comment by Bouni** [comment]
@mjiderhamn Where does this TLS certificate you mentioned come from?

**Comment by Bouni** [comment]
I found out whats different, it seems that they use a slightly different Amazon AWS IoT Endpoint,
`a1optpg91s0ydf-2.iot.eu-west-1.amazonaws.com` instead of `a1optpg91s0ydf.iot.eu-west-1.amazonaws.com`
With that endpoint I can connect again :-)
They also added some new data to the message sent by the 2.85 Firmware:
{ cfg: 
   { lg: 'it',
     tm: '06:19:05',
     dt: '09/10/2017',
     sc: { m: 1, p: 0, d: [Array] },
     cmd: 0,
     mz: [ 0, 0, 0, 0 ],
     mzv: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
     rd: 60,
     sn: '00000000000000000123' },
  dat: 
   { mac: 'DEADBEEFDEADBEEF',
     fw: 2.85,
     bt: { t: 15.7, v: 19.59, p: 83, nr: 3082, c: 0 },
     dmp: [ -1.2, 0.2, 10.8 ],
     st: { b: 9705, d: 180918, wt: 10351 },
     ls: 1,
     le: 5,
     lz: 0,
     rsi: -76,
     lk: 0 } }

**Comment by mjiderhamn** [comment]
From https://www.worxlandroid.com/en 

> Recently, some Landroid owners have experienced a WiFi connectivity issue preventing them from connecting to home networks. Despite using a world-class provider, this problem is related to our IoT cloud server provider. 
> While our provider fixes the issue, we have released a firmware upgrade optimizing communication traffic flow. We have tested it and it resolves the issue 100%. Please download and install this update and your Landroid will be able to connect again.

**Comment by Bouni** [comment]
@mjiderhamn 
Is it a viable option for you to just change the AWS endpoint, maybe make that configurable in case they change it again in the future? That solved the problem for me as I already mentioned above.

**Comment by mjiderhamn** [comment]
It can easily be changed [here](https://github.com/mjiderhamn/worx-landroid-nodejs/blob/master/landroid-cloud.js#L168)
