### ISSUE TITLE
node-red

### ISSUE THREAD

**Issue by mabunixda** [mjiderhamn/worx-landroid-nodejs#2]
Hi, 

are there any reportings on this library to use with node-red? 

Thanks, Martin

**Comment by mjiderhamn** [comment]
Hi @mabunixda . I haven't heard of anyone using it with [Node-RED](https://nodered.org/), though I'd assume it is fully possible. Feel free to contribute!

**Comment by mabunixda** [comment]
Hi @mjiderhamn 

Yeah there seems to exist nothing right now. Hope to get this on track by the start of mowing season ;-) ... when my worx arrived
