### ISSUE TITLE
Incompatible with Domoticz 3.x API

### ISSUE THREAD

**Issue by termdude** [mjiderhamn/worx-landroid-nodejs#2]
Tried to install with both the current stable and the latest beta of Domoticz, and it throws the following error. Anything fixable?

Making sure device exists: Worx Landroid Battery
Device missing, needs to be created: Worx Landroid Battery
Creating device Worx Landroid Battery with type 2
Response to type=createvirtualsensor&idx=0&sensortype=2: {"status":"ERR"}

/home/pi/worx-landroid-nodejs/domoticz.js:246
      throw "Error creating sensor '" + name + "': " + status;
                                                       ^
ReferenceError: status is not defined
    at /home/pi/worx-landroid-nodejs/domoticz.js:246:56
    at Object.najax.success (/home/pi/worx-landroid-nodejs/domoticz.js:103:9)
    at IncomingMessage.<anonymous> (/home/pi/worx-landroid-nodejs/node_modules/najax/lib/najax.js:130:44)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)

**Comment by mjiderhamn** [comment]
Hi @termdude . First of all, there seems to be a bug in the error handling in my code. I have tried fixing that. Would you care to try again with the latest version of my code, so we can continue debugging the Domoticz problem?

**Comment by termdude** [comment]
Hej Mattias,
Jag antar att du förstår svenska? ;) Jättetacksam för snabbt svar, för jag har letat efter denna funktion!

Jag testade igen och fick detta:

pi@domoticzpi ~/worx-landroid-nodejs $ nodejs ./landroid2domoticz.js 
Initializing devices on http://localhost
MQTT hardware found in Domoticz
Devices identified: {"VBin":7,"KBut":8,"Arbetsrummet":9,"KBin":10,"VBut":11,"Pannrummet":211,"":368,"Dörrklocka":300,"Signal 1":301,"Ute":331,"THB":365,"UV":367,"Total":386,"Värmepump":387,"Regn":388,"Or":407,"Råspont (HIH)":414,"Råspont":416,"Nock (innanför isolering)":417,"Unknown":469,"Solar Radiation":462,"Nexa 2":430,"Garaget":456,"Marktemp":457,"Pumptemp":458,"Orangeriet":463}
Making sure device exists: Worx Landroid Battery
Device missing, needs to be created: Worx Landroid Battery
Creating device Worx Landroid Battery with type 2
Response to type=createvirtualsensor&idx=0&sensortype=2: {"status":"ERR"}

/home/pi/worx-landroid-nodejs/domoticz.js:246
      throw "Error creating sensor '" + name + "': " + response.status;
                                                     ^
Error creating sensor 'Worx Landroid Battery': ERR

Jag har provat både med och utan en Dummy hardware...

-- 
Thomas Hertz

På 11 juli 2016 kl. 19:27:37, Mattias Jiderhamn (notifications@github.com) skrev:

Hi @termdude . First of all, there seems to be a bug in the error handling in my code. I have tried fixing that. Would you care to try again with the latest version of my code, so we can continue debugging the Domoticz problem?

**Comment by mjiderhamn** [comment]
Har du tittat i Domoticz loggar?

**Comment by termdude** [comment]
Japp, ingenting. Om jag manuellt skriver in kommandot i curl (http://domoticzpi.lan/json.htm?type=createvirtualsensor&idx=0&sensortype=2) så får jag följande svar:

{
   "status" : “ERR”
}


-- 
Thomas Hertz

På 11 juli 2016 kl. 21:33:22, Mattias Jiderhamn (notifications@github.com) skrev:

Har du tittat i Domoticz loggar?

**Comment by mjiderhamn** [comment]
I am able to recreate the issue after upgrading Domoticz from 2.2579 to 3.4834. Supposedly something changed in Domoticz API, although I don't notice any changes in [the documentation](https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s).

**Comment by mjiderhamn** [comment]
I have now made an update with the hopes of making it compatible with the Domoticz 3.x API. @termdude , could you give it another try?

**Comment by termdude** [comment]
Now it works like a charm, thanks alot!

-- 
Thomas Hertz

På 12 juli 2016 kl. 00:09:37, Mattias Jiderhamn (notifications@github.com) skrev:

I have now made an update with the hopes of making it compatible with the Domoticz 3.x API. @termdude , could you give it another try?
