### ISSUE TITLE
compatible with 2017 models?

### ISSUE THREAD

**Issue by Pastis67** [mjiderhamn/worx-landroid-nodejs#3]
Hello
Is it compatible with the new 2017 models ?

**Comment by mjiderhamn** [comment]
I haven't had any reports of incompatibility. On the other hand, I haven't heard of anyone that actually tried it, so I can't say. If you do try, please report back!

**Comment by MagnusKlingenberg** [comment]
The new 2017 models are not compatible with this package. The new models dont have any open ports but  call a cloud server on port 8883 so they are probably using secure mqtt. I havent been able reverse it yet but i will take a stab at it one day.

**Comment by Pastis67** [comment]
I have a WR106SI and no open ports on it :( thats so bad...

**Comment by mjiderhamn** [comment]
I have now started the work to integrate with the 2017 models. See [landroid-cloud.js](https://github.com/mjiderhamn/worx-landroid-nodejs/blob/master/landroid-cloud.js).

**Comment by Pastis67** [comment]
seems promising :)

**Comment by Pastis67** [comment]
seems promising :)  but I dont know how to get the guest token :\

**Comment by mjiderhamn** [comment]
The code [will download the guest token](https://github.com/mjiderhamn/worx-landroid-nodejs/blob/35a242d8046229bb8ac69e45b3fbf30416acbe5f/landroid-cloud.js#L37) automatically.

**Comment by Pastis67** [comment]
Any chance to get a domoticz integration ? :D

**Comment by mjiderhamn** [comment]
For Landroid 2017 models and Home Assistant, there is now documentation in the [README](https://github.com/mjiderhamn/worx-landroid-nodejs/blob/master/README.md). For Domoticz integration I have created #7 . Feel free to contribute! (Should be relatively easy to combine `landroid2domoticz.js` with `landroid-cloud2home-assistant.js`
