### ISSUE TITLE
How to get the raw data from the landroid

### ISSUE THREAD

**Issue by LordMax2** [mjiderhamn/worx-landroid-nodejs#4]
Hi!

I am wondering how the restful API is built, what parameters and headers need to be in it and what port is it working on. If an authentication token is needed how do I get it? I cannot find any good API documentation from WORX. Thanks in advance!

Best regards Max

**Comment by mjiderhamn** [comment]
For the 2015 models, I have documented the API [here](https://github.com/mjiderhamn/worx-landroid-nodejs/blob/master/landroid-api.md).

At one point I had documentation and implementation for more recent models as well, but received a Cease and Desist letter from Worx...
