### ISSUE TITLE
Worx 2017

### ISSUE THREAD

**Issue by gaslan1976** [mjiderhamn/worx-landroid-nodejs#5]
Hi, I have a WR105SI 2017 model. 

I've just installed under windows (with homeassistant), changed config.js with email/password/mac and homeassistant section (running to a rpi)..

Running the landroid2home-assistant.bat.bat i get the following output:

Starting Worx Landroid Home Assistant adapter
Scheduling polling
About to poll Landroid at http://landroid_s.local for status
Error communicating with Landroid!
Error getting update!
About to poll Landroid at http://landroid_s.local for status
Error communicating with Landroid!
Error getting update!
About to poll Landroid at http://landroid_s.local for status
Error communicating with Landroid!
Error getting update!

It seems to try to connect locally as a 2015-2016 and not trying to resolve through MQTT.. Is there an option to force the 2017 request method that I'm missing?

Thanks!!
George

**Comment by Pastis67** [comment]
> mjiderhamn commented Jun 29, 2017
I have now started the work to integrate with the 2017 models. See landroid-cloud.js.

Hello I think it is "in progress..." ;)

**Comment by mjiderhamn** [comment]
There is now information how to integrate the 2017 models with Home Assistant in the [README](https://github.com/mjiderhamn/worx-landroid-nodejs/blob/master/README.md).
